### ISSUE TITLE
Unable to build dependencies

### ISSUE THREAD

**Issue by jeffwack** [diagrams/diagrams#35] opened 2024-03-19 16:25 UTC
I following the [quickstart tutorial](https://diagrams.github.io/doc/quickstart.html) and am unable to proceed past the build step due to the dependency JuicyPixels. Here is the build log.

> Failed to build JuicyPixels-3.3.8.
Build log (
C:\cabal\logs\ghc-9.4.8\JuicyPixels-3.3.8-d0b6acc90ba048eb509563860bb12107f072db48.log
):
Preprocessing library for JuicyPixels-3.3.8..
Building library for JuicyPixels-3.3.8..
[ 1 of 30] Compiling Codec.Picture.InternalHelper ( src\Codec\Picture\InternalHelper.hs, dist\build\Codec\Picture\InternalHelper.o )       
[ 2 of 30] Compiling Codec.Picture.Metadata.Exif ( src\Codec\Picture\Metadata\Exif.hs, dist\build\Codec\Picture\Metadata\Exif.o )
[ 3 of 30] Compiling Codec.Picture.Metadata ( src\Codec\Picture\Metadata.hs, dist\build\Codec\Picture\Metadata.o )
[ 4 of 30] Compiling Codec.Picture.Tiff.Internal.Types ( src\Codec\Picture\Tiff\Internal\Types.hs, dist\build\Codec\Picture\Tiff\Internal\Types.o )
[ 5 of 30] Compiling Codec.Picture.Tiff.Internal.Metadata ( src\Codec\Picture\Tiff\Internal\Metadata.hs, dist\build\Codec\Picture\Tiff\Internal\Metadata.o )
[ 6 of 30] Compiling Codec.Picture.Types ( src\Codec\Picture\Types.hs, dist\build\Codec\Picture\Types.o )
ghc-9.4.8.exe: C:\cabal\store\ghc-9.4.8\zlib-0.6.3.0-d7b05d7718523872fdadd1c222d053c479e70007\lib\libHSzlib-0.6.3.0-d7b05d7718523872fdadd1c222d053c479e70007.a(#6:Stream.o): Not a x86_64 PE+ file.
ghc-9.4.8.exe: Unknown COFF 4 type in getHeaderInfo.

><no location info>: error:
    loadArchive "C:\\cabal\\store\\ghc-9.4.8\\zlib-0.6.3.0-d7b05d7718523872fdadd1c222d053c479e70007\\lib\\libHSzlib-0.6.3.0-d7b05d7718523872fdadd1c222d053c479e70007.a": failed
cabal-3.6.2.0-p1.exe: Failed to build JuicyPixels-3.3.8 (which is required by
exe:Diagrams from Diagrams-0.1.0.0). See the build log above for details.

**Comment by byorgey** [comment] 2024-03-20 02:42
Hi @jeffwack111 , thanks for the report!  I did a bit of Googling and it looks like this is a bug that was fixed in `cabal-3.8`: https://gitlab.haskell.org/ghc/ghc/-/issues/21990  Try upgrading to a newer version of `cabal` and see if that resolves the issue.

**Comment by jeffwack111** [comment] 2024-03-20 07:18
Thanks for the reply. This could be the issue, unfortunately I am having trouble upgrading to a newer version of cabal. I suppose this is no longer an issue for Diagrams... for what its worth after running "cabal install cabal-install", I get the following error message:

> "Build log (
C:\cabal\logs\ghc-9.4.8\cabal-install-3.10.2.1-756a3b8d0cd35636ee24a27bb96a5c6de0495fb9.log
):
Preprocessing executable 'cabal' for cabal-install-3.10.2.1..
Building executable 'cabal' for cabal-install-3.10.2.1..
[1 of 1] Compiling Main             ( main\Main.hs, dist\build\cabal\cabal-tmp\Main.o )
[2 of 2] Linking dist\\build\\cabal\\cabal.exe
ld.lld: error: undefined symbol: hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziLowLevel_hashInt_closure
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdfHashableInt_closure)
ld.lld: error: undefined symbol: ghczuwrapperZC1ZChashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fbZCDataziHashableziLowLevelZChashablezufnvzuhash
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdfHashable2ConstzuzdcliftHashWithSalt2_info)
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_hashPtr1_info)
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdwzdchashWithSalt4_slow)
>>> referenced 1 more times
ld.lld: error: undefined symbol: ghczuwrapperZC0ZChashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fbZCDataziHashableziLowLevelZChashablezufnvzuhashzuoffset
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdwgo2_info)
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_hashByteArray_info)
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdfHashableByteArrayzuzdchashWithSalt_info)
>>> referenced 21 more times
ld.lld: error: undefined symbol: hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziLowLevel_hashWord64_closure
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdfHashableWord64_closure)
ld.lld: error: undefined symbol: hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziLowLevel_hashInt64_closure
>>> referenced by libHShashable-1.4.3.0-6aa150cfd98536d070af2d7c96a3cc42751570fb.a(Class.o):(hashablezm1zi4zi3zi0zm6aa150cfd98536d070af2d7c96a3cc42751570fb_DataziHashableziClass_zdfHashableInt64_closure)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ghc-9.4.8.exe: `clang.exe' failed in phase `Linker'. (Exit code: 1)
Error: cabal-3.10.2.1.exe: Failed to build exe:cabal from
cabal-install-3.10.2.1. See the build log above for details."

**Comment by jeffwack111** [comment] 2024-04-12 01:17
Thank you. After reinstalling the Haskell toolchain with ghcup the issue is resolved.

**Closed as completed by jeffwack111** 2024-04-12 01:17 UTC
